### GET index
GET http://127.0.0.1:8000/

###

### POST api token
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "aluno1",
  "password": "Aluno@2025#"
}

> {% client.global.set("auth_token", response.body.access); %}

###

### GET dashboard
GET http://127.0.0.1:8000/dashboard?group=1&year=2025
Authorization: Bearer {{auth_token}}

###
