# Generated by Django 5.1.5 on 2025-02-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouphierarchy',
            name='is_supergroup',
            field=models.BooleanField(default=False),
        ),
    ]
